//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiHieuThuoc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vv_1
    {
        public string MaNV { get; set; }
        public string HoTen { get; set; }
        public string ChucVu { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> Ngaysinh { get; set; }
        public string Diachi { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public Nullable<System.DateTime> NgayLV { get; set; }
    }
}
